# Generated by Django 3.1.7 on 2021-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published'),
        ),
    ]
