# Generated by Django 3.1.7 on 2021-04-28 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_auto_20210422_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=31, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=31, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=63, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Price')),
                ('message', models.TextField(verbose_name='Description')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('company_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Company Name')),
                ('state', models.CharField(max_length=31, verbose_name='State')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Zip Code')),
                ('name_on_card', models.CharField(max_length=31, verbose_name='Name on Card')),
                ('card_number', models.BigIntegerField(verbose_name='Card Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('security_code', models.IntegerField(verbose_name='Security Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='product.product', verbose_name='Product')),
            ],
        ),
    ]
